GP_C_1_ProjectName-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home_page', as: 'home'

  get 'posts' => 'posts#index', as: 'posts'
  get 'forum' => 'forums#show', as: 'forum'
  get 'forum/new' => 'forums#new', as: 'forum/new'
  get 'forum/:forum/edit' => 'forums#edit', as: 'edit_forum'
  patch '/forum.:forum_id' => 'forums#update'
  post 'forum' => 'forums#create', :as => :create_forum
  delete "forum.:forum_id" => 'forums#destroy'
  forum_path = '/forum'
  get 'lobby' => 'lobby_requests#index', as: 'lobby'
  get 'about' => 'pages#about', as: 'about'
  get 'resources' => 'resources#index', as: 'resources'
  get 'profile' => 'profiles#index', as: 'profile'
  get 'messenger' => 'messengers#index', as: 'messenger'

  resources :lobby_requests
  resources :news_posts
  resources :announcements
  resources :posts do
    resources :comments
  end

end

GP_C_1_ProjectName-master/app/models/announcement.rb
class Announcement < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GP_C_1_ProjectName-master/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true,
                    length: {minimum: 1}
  validates :username, presence: true,
                    length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/forum.rb
class Forum < ApplicationRecord
  has_many :posts
  validates :name, presence: true,
                    length: {minimum: 5}
end

GP_C_1_ProjectName-master/app/models/lobby_request.rb
class LobbyRequest < ApplicationRecord
end

GP_C_1_ProjectName-master/app/models/news_post.rb
class NewsPost < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :body
end

GP_C_1_ProjectName-master/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :forum
  has_many :comments
  validates :title, presence: true,
                    length: {minimum: 5}

  validates :body, presence: true,
                   length: {minimum: 1}
end

GP_C_1_ProjectName-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

GP_C_1_ProjectName-master/app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def index
    @forums = Forum.all
  end

  def new
    @forum = Forum.new
  end

  def show
    @forums = Forum.all
  end

  def create
    @forum = Forum.new(forum_params)

    if(@forum.save)
      redirect_to forum_path
    else
      render 'new'
    end
  end

  def edit
    @forum = Forum.find(params[:forum])
  end

  def update
    @forum = Forum.find(params[:forum_id])

    if(@forum.update(forum_params))
      redirect_to forum_path
    else
      render 'edit'
    end
  end

  def destroy
    @forum = Forum.find(params[:forum_id])

    if(@forum.posts != nil)
      @posts = @forum.posts
      @posts.each do |post|
        if(post.comments != nil)
          @comments = post.comments
          @comments.each do |comm|
            comm.destroy
          end
        end
        post.destroy
      end
    end
    @forum.destroy
    redirect_to forum_path
  end

  private def forum_params
    params.require(:forum).permit(:name)
  end

end

GP_C_1_ProjectName-master/app/controllers/lobby_requests_controller.rb
class LobbyRequestsController < ApplicationController

  def index
    params[:sort] ||= "name"
    @lobby_requests = LobbyRequest.all
  end

  def new
    @lobby_request = LobbyRequest.new
  end

  def create
    @lobby_request = LobbyRequest.new(lobby_request_params)
    @lobby_request.name = current_user.email
    @lobby_request.time = (Time.now.hour*3600) + (Time.now.min*60) + (Time.now.sec)

    if(@lobby_request.save)
      redirect_to lobby_path
    else
      render 'new'
    end
  end

  def destroy
    @lobby_request = LobbyRequest.find(params[:id])
    @lobby_request.destroy

    redirect_to lobby_path
  end

  private def lobby_request_params
    params.require(:lobby_request).permit(:name, :game, :time)
  end

end

GP_C_1_ProjectName-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home_page
    @news_posts = NewsPost.all
    @announcements = Announcement.all
  end
end

GP_C_1_ProjectName-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
  end

  def new
    @post =  Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    @post.username = current_user.email

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if(@post.comments != nil)
      @comments = @post.comments
      @comments.each do |comm|
        comm.destroy
      end
        @post.destroy
    end
    redirect_to forum_path
  end

  private def post_params
    params.require(:post).permit(:username, :title, :body, :forum_id)
  end
end

GP_C_1_ProjectName-master/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

GP_C_1_ProjectName-master/app/helpers/application_helper.rb
module ApplicationHelper
end

GP_C_1_ProjectName-master/app/helpers/comments_helper.rb
module CommentsHelper
end

GP_C_1_ProjectName-master/app/helpers/forums_helper.rb
module ForumsHelper
end

GP_C_1_ProjectName-master/app/helpers/lobby_requests_helper.rb
module LobbyRequestsHelper

  def elapsedTime time
    elapsed = ((Time.now.hour*3600) + (Time.now.min*60) + (Time.now.sec)) - time
    if elapsed < 60
      output = (elapsed).to_s + "s"
    elsif elapsed < 3600
      output = (elapsed/60).to_s + "m"
    else
      ouput = (elapsed/3600).to_s + "h"
    end
    return output
  end

end

GP_C_1_ProjectName-master/app/helpers/messengers_helper.rb
module MessengersHelper
end

GP_C_1_ProjectName-master/app/helpers/news_posts_helper.rb
module NewsPostsHelper
end

GP_C_1_ProjectName-master/app/helpers/pages_helper.rb
module PagesHelper
end

GP_C_1_ProjectName-master/app/helpers/posts_helper.rb
module PostsHelper
end

GP_C_1_ProjectName-master/app/helpers/profiles_helper.rb
module ProfilesHelper
end

GP_C_1_ProjectName-master/app/helpers/resources_helper.rb
module ResourcesHelper
end

GP_C_1_ProjectName-master/app/views/lobby_requests/index.html.erb
<h1>Game Lobby</h1>
<!--<a href="/messenger">Messenger</a><br>-->

<body>There are currently <%= @lobby_requests.count  %> players online</body>

<!--<meta http-equiv="refresh" content="5"/> -->

<div id="table">
  <table style="width:100%" border="2" >
    <tr>
      <th>Player Name</th>
      <th>Game</th>
      <th>Last Active</th>
      <% if user_signed_in? %>
      <th>Remove/Accept</th>
      <% end %>
    </tr>
    <% for lobby_request in @lobby_requests %>
      <tr>
        <th><img src="https://t3.ftcdn.net/jpg/00/64/67/80/240_F_64678017_zUpiZFjj04cnLri7oADnyMH0XBYyQghG.jpg" style="width:50px;height:50px;"><a href= "<%= lobby_request.name %>/profile"><%= lobby_request.name %></a></th>
        <td><a href= "<%= lobby_request.game %>/community"><%= lobby_request.game %></a></td>
        <td><%= elapsedTime(lobby_request.time) %></td> <!-- Make into fuction -->
        <% if user_signed_in? %>
          <% if current_user.email == lobby_request.name %>
          <td><%= link_to 'Remove Request', lobby_request_path(lobby_request),
                                            method: :delete,
                                            data: { confirm: 'delet this??'},
                                            :class => 'btn btn-danger' %></td>
          <% else %>
          <td><%= link_to 'Accept Request', '#', :class => 'btn btn-success' %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<% if user_signed_in? %>
<%= link_to "New Request", new_lobby_request_path, :class => 'btn card text-white bg-secondary' %>
<% end %>

GP_C_1_ProjectName-master/app/views/lobby_requests/new.html.erb
<h1>New Lobby Request</h1>

<%= form_for :lobby_request, url: lobby_requests_path do |f| %>
  <%if @lobby_request.errors.any? %>
    <% @lobby_request.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :game %><br>
    <%= f.text_field(:game, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-secondary'}) %>
  </p>
<% end %>